# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/derekhe"
  #weibo: "http://weibo.com/h198505"
  rss: "http://www.april1985.com/atom.xml"
  #zhihu: "#"
  #douban: "#"
  mail: "derekhe@april1985.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  linkedin: "https://cn.linkedin.com/pub/sicong-he/27/9b3/b71"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
favicon: /favicon.png

#你的头像url
avatar: "https://avatars1.githubusercontent.com/u/1734077?v=3&s=460"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
uyan: true
#是否开启云标签
tagcloud: true